<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SACHIN" name="Test(failed)" tests="3" failures="1" timestamp="30 Apr 2021 06:45:03 GMT" time="0.165" errors="0">
  <testcase name="testcase1" time="0.046" classname="TestNG_Disscussion.SkippedTestCase"/>
  <testcase name="testcase2" time="0.01" classname="TestNG_Disscussion.SkippedTestCase">
    <failure type="java.lang.AssertionError" message="test case got failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: test case got failed expected [false] but found [true]
	at TestNG_Disscussion.SkippedTestCase.testcase2(SkippedTestCase.java:21)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase3" time="0.0" classname="TestNG_Disscussion.SkippedTestCase2">
    <skipped/>
  </testcase> <!-- testcase3 -->
</testsuite> <!-- Test(failed) -->
